# Generated by Django 3.2.3 on 2021-05-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='klas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.klas', verbose_name='Клас'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='strana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='firstapp.strana', verbose_name='Страна'),
        ),
    ]
