# Generated by Django 3.2.3 on 2021-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210523_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klas',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Класcы'},
        ),
        migrations.AddField(
            model_name='tank',
            name='silka',
            field=models.CharField(max_length=70, null=True, verbose_name='Ссылка'),
        ),
    ]
