# Generated by Django 3.2.3 on 2021-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210530_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['-id'], 'verbose_name': 'Танк', 'verbose_name_plural': 'Танки'},
        ),
        migrations.AddField(
            model_name='tank',
            name='publish',
            field=models.BooleanField(blank=True, null=True, verbose_name='Галочка публикации'),
        ),
    ]
