# Generated by Django 3.2.3 on 2021-06-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210610_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='publish',
            field=models.BooleanField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
