# Generated by Django 3.2.3 on 2021-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_tank_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='klas',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='strana',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
